program: main.py
name: sweep_xl_models_ada6000_gpu0
method: random
metric:
  goal: minimize
  name: validation_loss
parameters:
  learning_rate:
    values: [0.001, 0.0001, 0.00001, 0.000005]
  batch_size:
    values: [4, 8, 16, 32]  # Conservative for XL model
  epochs:
    values: [4, 8, 16]
  target_seq_len:
    values: [8, 16, 32, 64, 128]
  source_seq_len:
    values: [8, 16, 32, 64, 128]
  optimizer:
    values: ["adamw", "adam"]
  hf_model_name:
    values: [
      "google-t5/t5-3b",
      "google/t5-3b-ssm-nq",
      "google/flan-t5-xl",  # 2.85B parameters 
      "google/t5-efficient-xl-nl28",
      "google/t5-efficient-xl-nl2"
    ]
