# configs/server1/sweep_t5_11b_ada6000_4bit.yaml
program: main.py
name: sweep_t5_11b_ada6000_4bit
method: grid
metric:
  goal: minimize
  name: validation_loss
parameters:
  learning_rate:
    values: [1e-4, 5e-5, 1e-5]
  batch_size:
    values: [1, 2]
  gradient_accumulation_steps:
    values: [4, 8, 16, 32]
  epochs:
    values: [2, 4]
  target_seq_len:
    values: [8, 16, 32, 64, 128]
  source_seq_len:
    values: [8, 16, 32, 64, 128]
  optimizer:
    values: ["adamw"]
  hf_model_name:
    values: ["iarroyof/t5-11b-ssm-nq-sharded", "google/t5_xxl_true_nli_mixture"]
  quantization:
    values: ["4bit"]
