program: seq2seq_T5.py
name: sweepT5
method: random
metric:
  goal: minimize
  name: validation_loss
parameters:
  learning_rate:
    min: 0.0001
    max: 0.1
  batch_size:
    values: [16, 32, 64, 128]
  epochs:
    values: [2, 5, 10]
  optimizer:
    values: ["adam", "adamw"]