program: ES_T5_seq2seq.py
name: SweepT5
method: random
metric:
  goal: minimize
  name: validation_loss
parameters:
  learning_rate:
    values: [0.001, 0.0001, 0.00001, 0.0000055] #0.000001]
  batch_size:
    values: [4, 8, 16, 32]
  epochs:
    values: [2, 4, 8]
  target_seq_len:
    values: [10, 50, 100, 200]
  source_seq_len:
    values: [10, 50, 100, 200]
  optimizer:
    values: ["adam", "adamw", "sgd", "asgd"]
  hf_model_name:
    values: ["t5-small", "t5-base", "t5-large", "google/t5-v1_1-base"]
    #values: ["t5-small", "t5-base", "t5-large", "google/t5-v1_1-base", "google/flan-t5-base", "google/flan-t5-large", "google/flan-ul2", "google/umt5-small", "google/umt5-base"]
