program: seq2seq_T5.py
name: sweepT5
method: random
metric:
  goal: minimize
  name: validation_loss
parameters:
  learning_rate:
    values: [0.1, 0.01, 0.001, 0.0001, 0.00001]
  batch_size:
    values: [4, 8, 16, 32, 64]
  epochs:
    values: [2, 4, 8]
  optimizer:
    values: ["adam", "adamw"]