wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.40.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714164726.0
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      3:
      - 2
      - 23
      - 37
      4: 3.11.9
      5: 0.16.6
      6: 4.40.1
      8:
      - 5
      13: linux-x86_64
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 0.06387447279232115
optimizer:
  desc: null
  value: adamw
