program: main.py
name: sweep_small_multi_rtx4090_2_gpu1
method: random
metric:
  goal: minimize
  name: validation_loss
parameters:
  learning_rate:
    values: [0.001, 0.0001, 0.00001, 0.000005]
  batch_size:
    values: [16, 32, 64, 96, 128]
  epochs:
    values: [4, 8, 16]
  target_seq_len:
    values: [8, 16, 32, 64, 128]
  source_seq_len:
    values: [8, 16, 32, 64, 128]
  optimizer:
    values: ["adamw", "adam"]
  hf_model_name:
    values: [
      "google/mt5-small",
      "google/umt5-small",
      "gayanin/bart-finetuned-pubmed",
      "gayanin/t5-small-finetuned-pubmed",
      "google/pegasus-pubmed"
    ]
