program: main.py
name: sweep_small_t5_rtx4090_2_gpu0
method: grid
metric:
  goal: minimize
  name: final_test_loss
parameters:
  learning_rate:
    values: [0.001, 0.0001, 0.00001, 0.000005]
  batch_size:
    values: [16, 32, 64, 96, 128]  # Larger batches for small models
  epochs:
    values: [4, 8, 16]
  target_seq_len:
    values: [8, 16, 32, 64, 128]
  source_seq_len:
    values: [8, 16, 32, 64, 128]
  optimizer:
    values: ["adamw", "adam"]
  hf_model_name:
    values: [
      "t5-small",
      "google/t5-v1_1-small",
      "google/flan-t5-small",
      "facebook/bart-large"
    ]
