program: main.py
name: sweep_base_models_rtx4090_1_gpu0
method: random
metric:
  goal: minimize
  name: validation_loss
parameters:
  learning_rate:
    values: [0.001, 0.0001, 0.00001, 0.000005]
  batch_size:
    values: [8, 16, 32, 64, 96]
  epochs:
    values: [4, 8, 16]
  target_seq_len:
    values: [8, 16, 32, 64, 128]
  source_seq_len:
    values: [8, 16, 32, 64, 128]
  optimizer:
    values: ["adamw", "adam"]
  hf_model_name:
    values: [
      "facebook/bart-base",
      "google/pegasus-gigaword",
      "google/mt5-base"
    ]
