# -*- coding: utf-8 -*-
"""LLM_JUEZ_actualizado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12JfL9v7iWL9JBBXKRHXT6O9mm3AYKUjg
"""

# ── Imports ────────────────────────────────────────────────────────────────
import pandas as pd
import json
import re
import random
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

model_name = "Qwen/Qwen2-1.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16,
    device_map="auto"
)

# ── Cargar reseñas SINTÉTICAS (todas) ─────────────────────────────────────
df_input = pd.read_csv("data/synthetic_reviews.csv")
print(f"✅ Sintéticas cargadas: {len(df_input)} filas")

data = df_input[["Text", "Polarity"]].dropna().to_dict(orient="records")

print(f"✅ {len(data)} reseñas sintéticas seleccionadas")
print(pd.Series([r["Polarity"] for r in data]).value_counts().sort_index())

# ── Cargar reseñas REALES (todas) ─────────────────────────────────────────
df_train = pd.read_csv("data/train.csv")
print(f"✅ Train cargado: {len(df_train)} reseñas reales")

train_sample = df_train[["Review", "Polarity"]].dropna()

# Índice por polaridad para recuperar ejemplos rápido
train_by_polarity = {
    int(p): grp["Review"].tolist()
    for p, grp in train_sample.groupby("Polarity")
}

print(f"✅ {len(train_sample)} reseñas reales disponibles como referencia")
print(train_sample["Polarity"].value_counts().sort_index())

# ── Prompt con reseñas reales de referencia por polaridad ─────────────────
def build_prompt(text, label, n_ejemplos=2):
    ejemplos = random.sample(
        train_by_polarity[int(label)],
        k=min(n_ejemplos, len(train_by_polarity[int(label)]))
    )
    ejemplos_str = "\n".join([f'- "{e[:300]}"' for e in ejemplos])

    return f"""
Eres un evaluador experto en generación de texto sintético para turismo en México.

A continuación tienes {n_ejemplos} reseñas REALES con polaridad {label} como referencia:
{ejemplos_str}

Ahora evalúa esta reseña SINTÉTICA con polaridad {label}:
"{text}"

Evalúa del 1 al 5 comparando con las reseñas reales:
- Realismo
- Riqueza
- Diversidad
- Coherencia
- Alineación de sentimiento
- Utilidad para clasificación


Responde SOLO en JSON:
{{
  "realismo": int,
  "riqueza": int,
  "diversidad": int,
  "coherencia": int,
  "alineacion_sentimiento": int,
  "utilidad_clasificacion": int

}}
"""

def evaluate_with_qwen(prompt):
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    outputs = model.generate(
        **inputs,
        max_new_tokens=200,
        do_sample=False
    )

    response = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[-1]:],
        skip_special_tokens=True
    )

    return response

def extract_json(text):
    try:
        matches = re.findall(r'\{[^{}]*\}', text)
        for m in matches:
            return json.loads(m)
    except Exception as e:
        print("Error parsing:", e)
    return None

results = []

for i, r in enumerate(data):
    print(f"Evaluando {i+1}/{len(data)}...")
    prompt = build_prompt(r["Text"], r["Polarity"])
    response = evaluate_with_qwen(prompt)
    scores = extract_json(response)

    if scores:
        results.append({**r, **scores})
    else:
        print(f"  ⚠️ Sin JSON válido en fila {i+1}:", response[:100])

df_out = pd.DataFrame(results)

cols = [
    "realismo", "riqueza", "diversidad", "coherencia",
    "alineacion_sentimiento", "utilidad_clasificacion"
]

for c in cols:
    if c not in df_out.columns:
        df_out[c] = None

df_out["score_final"] = df_out[cols].astype(float).mean(axis=1)

print(df_out)

if not df_out["score_final"].isna().all():
    print("\nScore promedio:", df_out["score_final"].mean())
    print("\nScore promedio por polaridad:")
    print(df_out.groupby("Polarity")["score_final"].mean())
else:
    print("\nNo hay scores válidos")

df_out.to_csv("resultados_qwen_juez.csv", index=False)
print("✅ Guardado en resultados_qwen_juez.csv")