# configs/es_config.yaml
ElasticSearch:
  url: "http://192.168.241.210:9200"
  index: "triplets"
  es_page_size: 500
  n_sentences: 5000
  article_ids_file: "data/lung_cancer_es_ids.txt"
  n_articles: 10000
